# -*- coding: utf-8 -*-
"""DAtask1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ASA0cwMtx4Ho0tL06ZcMI7bL-TQHU3rK
"""

print('Hello World') # display the welcome message using print

Name = input('Whats your Name?') # taking input from user
Age = input('How old are you?')
Hobby = input("What is your favorite hobby? ")
print(f"\n Welcome {Name}!")
print(f"You are {Age} years old and love {Hobby}.") #Display a personalized message

# Taking input from user
print('Maths Calculation')
a = input("Enter first number: ")
b = input("Enter second number: ")

# Convert to numbers
a = float(a)
b = float(b)

# Perform calculations
print("\n--- Results ---")
print(f"Addition: {a + b}")
print(f"Subtraction: {a - b}")
print(f"Multiplication: {a * b}")
print(f"Division: {a / b}")

food = ["Pizza","Biriyani","Rice","Loaded fries"] #listing favourite food
print('/n Favorite food')
print('Favourite food:',food[3])

print('/n ---Bio Data---') #display biodata
print('Name:',Name)
print('Age:',Age)
print('Hobby:',Hobby)